apiVersion: v1
kind: PersistentVolumeClaim 
metadata: 
  name: postgres-pv-claim
  labels:
    app: fullstack-postgres
spec: 
  storageClassName: manual 
  accessModes:
    - ReadWriteMany  
  resources:
    requests:
      storage: 10Gi