apiVersion: v1  
kind: Service                   
metadata:
  name: crime-detail-api-endpoint     
  namespace:  api-services
  labels:                          
    app: crime-detail-api-endpoint
spec:
  type: NodePort  
  selector:
    app: crime-detail-api-endpoint  
  ports: 
  - name: http
    port: 8080
    targetPort: 8080
        

